spring:
  datasource:
    url: jdbc:postgresql://localhost:49153/postgres
    username: postgres
    password: postgrespw
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  jackson:
    default-property-inclusion: non_null
  sql:
    init:
      mode: always

cloud:
  aws:
    region:
      static: eu-central-1
      auto: false
    stack:
      auto: false
    credentials:
        accessKey:
        secretKey:

logging:
  level:
    com:
      amazonaws:
        internal:
          com.amazonaws.internal.InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error

server:
  error:
    include-exception: false
    include-stacktrace: never
    include-message: never
    include-binding-errors: always