spring:
  datasource:
    url: jdbc:postgresql://localhost:49153/postgres
    username: postgres
    password: postgrespw
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  jackson:
    default-property-inclusion: non_null
  sql:
    init:
      mode: always